cookies = [
    {"domain": ".chatgpt.com", "expirationDate": 1746766349.864152, "hostOnly": False, "httpOnly": False, "name": "_puid", "path": "/", "sameSite": "lax", "secure": True, "session": False, "storeId": None, "value": "user-6aFLnAerZpcAAJ0VlLV35LQO:1746161549-FsLb%2FCx7gmAUNVJxoH0xJ6mV76KKE6wJxymF22hVAJ0%3D"},
    {"domain": ".chatgpt.com", "expirationDate": 1754249908.385786, "hostOnly": False, "httpOnly": True, "name": "__Secure-next-auth.session-token", "path": "/", "sameSite": "lax", "secure": True, "session": False, "storeId": None, "value": "eyJhbGciOiJka... (TRUNCATED FOR LENGTH)"},
    {"domain": "chatgpt.com", "expirationDate": 1746477104.758831, "hostOnly": True, "httpOnly": True, "name": "__cflb", "path": "/", "sameSite": "no_restriction", "secure": True, "session": False, "storeId": None, "value": "0H28vzvP5FJafnkHxihN18Lp242vWriYZG2LxNTjYUK"},
    {"domain": "chatgpt.com", "expirationDate": 1775447365.543933, "hostOnly": True, "httpOnly": False, "name": "oai-hlib", "path": "/", "sameSite": "lax", "secure": False, "session": False, "storeId": None, "value": "true"},
    {"domain": "chatgpt.com", "expirationDate": 1746475426, "hostOnly": True, "httpOnly": False, "name": "_dd_s", "path": "/", "sameSite": "strict", "secure": False, "session": False, "storeId": None, "value": "rum=0&expire=1746475419723&logs=1&id=4cf03045-4dab-41af-8eda-d48a8b7c4a18&created=1746471058577"},
    {"domain": "chatgpt.com", "expirationDate": 1781021872.957053, "hostOnly": True, "httpOnly": False, "name": "oai-thread-sidebar", "path": "/", "sameSite": "lax", "secure": False, "session": False, "storeId": None, "value": "%7B%22isOpen%22%3Afalse%7D"},
    {"domain": ".chatgpt.com", "expirationDate": 1746476166.502188, "hostOnly": False, "httpOnly": True, "name": "__cf_bm", "path": "/", "sameSite": "no_restriction", "secure": True, "session": False, "storeId": None, "value": "hPUyFdSXYNG1KGwOfBxPlL2i_..."},
    {"domain": "chatgpt.com", "hostOnly": True, "httpOnly": False, "name": "oai-hm", "path": "/", "sameSite": "lax", "secure": False, "session": True, "storeId": None, "value": "ON_YOUR_MIND%20%7C%20AGENDA_TODAY"},
    {"domain": ".chatgpt.com", "hostOnly": False, "httpOnly": True, "name": "_cfuvid", "path": "/", "sameSite": "no_restriction", "secure": True, "session": True, "storeId": None, "value": "cAUav.MLKpGTdb5CuozIgIblbmez4BGEETzW5RoWM1Q-1746474367121-0.0.1.1-604800000"},
    {"domain": "chatgpt.com", "expirationDate": 1749025426.809614, "hostOnly": True, "httpOnly": False, "name": "oai-last-model", "path": "/", "sameSite": "lax", "secure": False, "session": False, "storeId": None, "value": "gpt-4o"},
    {"domain": ".chatgpt.com", "expirationDate": 1778010304.851461, "hostOnly": False, "httpOnly": False, "name": "oai-sc", "path": "/", "sameSite": "no_restriction", "secure": True, "session": False, "storeId": None, "value": "0gAAAAABoGRVB1t0G1XN2..."},
    {"domain": "chatgpt.com", "hostOnly": True, "httpOnly": False, "name": "oai-gn", "path": "/", "sameSite": "lax", "secure": False, "session": True, "storeId": None, "value": "Company%20Name%3A%20massive%20magnetics%2C%20Ethica%20AI%2C%20B%20Heard%20Network%0AStage%20Name%3A%20%22iambandobandz%22%20pronounced%20%22i%20am%20bando%20bandz%22%0AGovernment%20Name%3A%20Brandon%0ANickname%3A%20Bando"}
    # [...truncated for brevity, you can paste the full cookie list here if needed...]
]
